### PR TITLE
Release/4.1.3

### PR DESCRIPTION
**Pull request by RCGitBot**
### Other Changes
* `automaticAppleSearchAdsAttributionCollection`: changed implementation to call method directly (#199) via NachoSoto (@NachoSoto)
 * Release train (#202) via Cesar de la Vega (@vegaro)
 * Adds Danger (#204) via Cesar de la Vega (@vegaro)
 * Upgrade iOS to 4.10.2 (#207) (@NachoSoto)

### CODE REVIEW

**Comment by NachoSoto** [comment]
As mentioned in Slack, this automatic release looks off. It includes a change that’s already in the previous release, and it didn’t bump iOS to 4.10.2.

**Comment by vegaro** [comment]
I regenerated the changelog locally and updated this branch. https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/28 has the fix

**Comment by NachoSoto** [comment]
Can we wait for #207?

**Comment by NachoSoto** [comment]
This should be ready now @vegaro, thanks for helping!

**Review by taquitos — APPROVED** [review]
All aboard the release train!
ChooChoo

**Comment by NachoSoto** [comment]
Looks like something needs updating: https://app.circleci.com/pipelines/github/RevenueCat/purchases-hybrid-common/1152/workflows/5f077e6b-cc6d-49cf-a6b8-713d23e1870d/jobs/2755

**Comment by vegaro** [comment]
looking into the issue

**Comment by vegaro** [comment]
Release completed!

**Pull request merged**
