### PR TITLE
Upgrade iOS to 4.10.2

### PR DESCRIPTION
**Pull request by NachoSoto**
Upgrade iOS to 4.10.2.

### CODE REVIEW

**Review by tonidero — APPROVED** [review]
Hmm this doesn't actually update Android at all... I think @vegaro fixed that so only the version updated showed... Did you do this PR automatically or manually? In any case, looks good.

**Comment by tonidero** [comment]
Oh tests seems to be failing though

**Comment by NachoSoto** [comment]
I did this manually. 

I still need to fix the iOS build though.

**Comment by NachoSoto** [comment]
Updated the tests for the `internal` API change in the SDK.

**Pull request merged**
