### PR TITLE
[AUTOMATIC] Release/6.2.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### Dependency Updates
* [AUTOMATIC] iOS 4.25.10 => 4.26.0 (#498) via RevenueCat Git Bot (@RCGitBot)
### Other Changes
* Trigger automatic PHC updates in Capacitor plugin (#497) via Toni Rico (@tonidero)

### CODE REVIEW

**Comment by tonidero** [comment]
I'm going to close this. The changes in iOS, shouldn't really affect the hybrids (it's mostly paywalls related).

**Comment by vegaro** [comment]
Ok, I shouldn't have merged the other PR? I thought it would be fine to just have it up to date even if it was just paywalls

**Comment by NachoSoto** [comment]
There's some other changes but yeah there's no rush to release it.

**Comment by tonidero** [comment]
> Ok, I shouldn't have merged the other PR? I thought it would be fine to just have it up to date even if it was just paywalls

Hmm, I mean, we can... Hybrids shouldn't see any changes from what I could see, but if we want to avoid huge releases in the hybrids later, I'm ok if we want to do this.

> There's some other changes but yeah there's no rush to release it.

Yeah, I saw them, but none of them seem like they would affect the hybrids. Do lmk if I'm wrong and happy to make this release.

**Pull request closed without merging**
