### PR TITLE
[AUTOMATIC] iOS 4.15.3 => 4.15.4

### PR DESCRIPTION
**Pull request by RCGitBot**
[AUTOMATIC] iOS 4.15.3 => 4.15.4

### CODE REVIEW

**Review by NachoSoto — APPROVED** [review]

**Comment by vegaro** [comment]
@NachoSoto do you know what's up with the tests?

**Comment by vegaro** [comment]
They say Flaky but I've never seen them fail I think

**Comment by NachoSoto** [comment]
Yeah I think it might me something legitimate. I have a flight this morning and then I'll have like 3 hours off so I'll dig into it. Also we should have a better error message.

**Comment by NachoSoto** [comment]
```
2022-12-16 09:02:43.183147-0800 PurchasesHybridCommonIntegrationTestApp[14150:3954994] [Purchases] - ERROR: 💰 Product purchase for 'com.revenuecat.purchases_hybrid_common.monthly_19.99_.1_week_intro' failed with error: Error Domain=RevenueCat.ErrorCode Code=8 "The receipt is not valid. The purchased product was missing in the receipt. This is typically due to a bug in StoreKit." UserInfo={source_function=convertUnsuccessfulResponseToError(), NSLocalizedDescription=The receipt is not valid. The purchased product was missing in the receipt. This is typically due to a bug in StoreKit., rc_backend_error_code=7712, source_file=RevenueCat/HTTPClient.swift:380, NSUnderlyingError=0x600003188060 {Error Domain=RevenueCat.BackendErrorCode Code=7712 "The purchased product was missing in the receipt. This is typically due to a bug in StoreKit." UserInfo={NSLocalizedDescription=The purchased product was missing in the receipt. This is typically due to a bug in StoreKit., rc_backend_error_code=7712}}, readable_error_code=INVALID_RECEIPT, rc_response_status_code=422}
2022-12-16 09:02:43.183607-0800 PurchasesHybridCommonIntegrationTestApp[14150:3954752] [Purchases] - ERROR: 😿‼️ Unknown error.
```

**Comment by NachoSoto** [comment]
Fixed bad error reporting: https://github.com/RevenueCat/purchases-ios/pull/2165

Now looking into why we're failing to post the purchase.

**Comment by NachoSoto** [comment]
I think this will fix the failures: #279.

**Pull request merged**
